sudo: required

language: php

php:
  -

services:
  - docker

env:
  -

before_install:
  - openssl aes-256-cbc -K $encrypted_80d99b7f2682_key -iv $encrypted_80d99b7f2682_iv -in deploy.enc -out deploy -d
  - mkdir mysql_build
  - cd mysql_build
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/docker/dockerfiles/mysql/init.sql
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/docker/dockerfiles/mysql/Dockerfile
  - docker build -t egc/mysql .
  - docker network create --subnet=172.18.0.0/16 dev
  - docker run -d --network=dev --ip=172.18.2.2 -e MYSQL_ROOT_PASSWORD=nothing egc/mysql
  - cd ..
  # FIN DEL DESPLIEGUE, YA SE PUEDEN REALIZAR TESTS CON LA BD

before_deploy:
  - chmod 600 deploy && mv deploy ~/.ssh/id_rsa
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/tools/deploy.sh
  # ADMINISTRACIÓN DE VOTACIONES: DESCOMENTAR SIGUIENTE LÍNEA
  # - scp target/*.war deploy@egc.duckdns.org:g2/tmp/ROOT.war

deploy:
  skip_cleanup: true
  provider: script
  script: ssh -o StrictHostKeyChecking=no deploy@egc.duckdns.org 'bash -s' < deploy.sh recuento_votos
  on:
    branch: master
